services:

  mssql:
    container_name: mssql-db
    hostname: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Passw0rd
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: Express
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P Passw0rd -Q 'SELECT 1' -C" ]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - devsu_network
                
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s
    networks:
      - devsu_network
           
  app-devsucustomer-api:
    build:
      context: ../.
      dockerfile: ./src/DevsuCustomer.Api/Dockerfile
    container_name: 'devsucustomer-api'
    depends_on:
      rabbitmq:
        condition: service_healthy
      mssql:
        condition: service_healthy
    ports:
      - "8090:8080"
      - "8091:8081"
    networks:
      - devsu_network
        
  app-devsuaccount-api:
    build:
      context: ../.
      dockerfile: ./src/DevsuAccount.Api/Dockerfile
    container_name: 'devsuaccount-api'
    depends_on:
      rabbitmq:
        condition: service_healthy
      mssql:
        condition: service_healthy  
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - devsu_network
  
networks:
  devsu_network:
    driver: bridge